### ISSUE TITLE
No links and edges shown on rviz

### ISSUE THREAD

**Issue by aaravrav142** [sauravag/slam_karto_g2o#1]
Hi, 
Thanks for this package. I have been using the original karto package so far. I found that unlike the original package this package does not produce any links and edges on the map (rviz), only the nodes are shown. Can you confirm this? Thanks

**Comment by sauravag** [comment]
Yes that's correct. Drawing the edges was slowing down the visualization so as of now I have disabled it. Have a look at the getGraph function in G2OSolver and you can Uncomment the part where edges are computed

**Comment by aaravrav142** [comment]
Hi, 
Thanks for the reply. 

Do you mean these two lines
```
//HyperGraph::VertexIDMap vertexMap = optimizer_.vertices();

  //HyperGraph::EdgeSet edgeSet = optimizer_.edges();
```
I cannot find anything commented inside the G2OSolver.h.
Thanks
